src/ContabilizaJa.WebApp/Models/ErrorViewModel.cs
using System;

namespace ContabilizaJa.WebApp.Models
{
    public class ErrorViewModel
    {
        public string RequestId { get; set; }

        public bool ShowRequestId => !string.IsNullOrEmpty(RequestId);
    }
}

src/ContabilizaJa.WebApp/Controllers/BaseController.cs
using ContabilizaJa.Processamento.ApplicationCore.Notifications;
using MediatR;
using Microsoft.AspNetCore.Hosting;
using Microsoft.AspNetCore.Mvc;
using System;
using System.Collections.Generic;
using System.Linq;
using System.Threading.Tasks;

namespace ContabilizaJa.WebApp.Controllers
{
    public class BaseController : Controller
    {
        private readonly IHostingEnvironment _appEnvironment;
        private readonly DomainNotificationHandler _notifications;
        protected Guid ClienteId = Guid.Parse("4885e451-b0e4-4490-b959-04fabc806d32");

        public BaseController(IHostingEnvironment env,
                              INotificationHandler<DomainNotification> notifications)
        {
            _appEnvironment = env;
            _notifications = (DomainNotificationHandler)notifications;
        }

        public IEnumerable<string> ObterMensagens()
        {
            return _notifications.ObterNotificacoes().Select(c => c.Mensagem).ToList();
        }

        public string GetPathRootFiles()
        {
            return _appEnvironment.WebRootPath;
        }
    }
}

src/ContabilizaJa.WebApp/Controllers/ExtratoBancarioController.cs
using ContabilizaJa.Movimentacao.Data.Queries;
using ContabilizaJa.Processamento.ApplicationCore.Commands;
using ContabilizaJa.Processamento.ApplicationCore.Notifications;
using ContabilizaJa.Processamento.CrossCutting;
using ContabilizaJa.Processamento.Domain;
using MediatR;
using Microsoft.AspNetCore.Hosting;
using Microsoft.AspNetCore.Mvc;
using System;
using System.Collections.Generic;
using System.Linq;
using System.Threading.Tasks;

namespace ContabilizaJa.WebApp.Controllers
{
    public class ExtratoBancarioController : BaseController
    {
        private readonly IExtratoBancarioQueries _extratoBancarioQueries;
        private readonly IMediator _mediator;

        public ExtratoBancarioController(IHostingEnvironment env,
                                         INotificationHandler<DomainNotification> notifications,
                                         IExtratoBancarioQueries extratoBancarioQueries,
                                         IMediator mediator) : base(env, notifications)
        {
            _extratoBancarioQueries = extratoBancarioQueries;
            _mediator = mediator;
        }

        [HttpGet]
        public async Task<IActionResult> Index()
        {
            var todosExtratos = await _extratoBancarioQueries.ObterListaDeExtratos();

            return View("Index", todosExtratos);
        }

        [HttpGet("BuscarExtratos")]
        public async Task<IActionResult> Get()
        {
            var todosExtratos = await _extratoBancarioQueries.ObterListaDeExtratos();

            return View("Index", todosExtratos);
        }

        [HttpGet("ConsultarExtrato/{id:int}")]
        public async Task<IActionResult> Get(int id)
        {
            var extrato = await _extratoBancarioQueries.ConsultarExtrato(id);

            return View("Transacoes/TransacoesBancarias", extrato);
        }

        [HttpPost("CadastrarExtrato")]
        public async Task<IActionResult> Post([FromBody] IEnumerable<TransacoesBancaria> extrato)
        {
            var extratoTransacoes = new AdicionarExtratoBancarioCommand
            {
                ExtratoBancario = ConverterTransacoesBancariaParaViewModel.ConverterTipo(extrato)
            };

            var resultado = await _mediator.Send(extratoTransacoes);

            return Json(new { success = resultado, message = ObterMensagens().FirstOrDefault()});
        }

        [HttpDelete("Remover/{id:int}")]
        public async Task<IActionResult> Delete(int id)
        {
            var extratoId = new RemoverExtratoBancarioCommand { IdExtrato = id };

            var resultado = await _mediator.Send(extratoId);

            if (resultado)
                ViewData["Success"] = ObterMensagens();
            else
                ViewData["Error"] = ObterMensagens();

            return View("Index");
        }
    }
}

src/ContabilizaJa.WebApp/Controllers/HomeController.cs
using ContabilizaJa.WebApp.Models;
using Microsoft.AspNetCore.Mvc;
using System;
using System.Collections.Generic;
using System.Diagnostics;
using System.Linq;
using System.Threading.Tasks;

namespace ContabilizaJa.WebApp.Controllers
{
    public class HomeController : Controller
    {
        public IActionResult Index()
        {
            return View();
        }

        public IActionResult Privacy()
        {
            return View();
        }

        [ResponseCache(Duration = 0, Location = ResponseCacheLocation.None, NoStore = true)]
        public IActionResult Error()
        {
            return View(new ErrorViewModel { RequestId = Activity.Current?.Id ?? HttpContext.TraceIdentifier });
        }
    }
}

src/ContabilizaJa.WebApp/Controllers/ProcessarArquivoController.cs
using ContabilizaJa.Processamento.ApplicationCore.Commands;
using ContabilizaJa.Processamento.ApplicationCore.Notifications;
using ContabilizaJa.Processamento.CrossCutting;
using MediatR;
using Microsoft.AspNetCore.Hosting;
using Microsoft.AspNetCore.Http;
using Microsoft.AspNetCore.Mvc;
using System;
using System.Collections.Generic;
using System.IO;
using System.Linq;
using System.Threading.Tasks;
using usandoIO = System.IO;

namespace ContabilizaJa.WebApp.Controllers
{
    public class ProcessarArquivoController : BaseController
    {
        private readonly IMediator _mediator;

        public ProcessarArquivoController(IHostingEnvironment env,
                                          INotificationHandler<DomainNotification> notifications,
                                          IMediator mediator) : base(env, notifications)
        {
            _mediator = mediator;
        }

        public IActionResult Index()
        {
            return View();
        }

        [HttpPost]
        public IActionResult CarregarArquivo(List<IFormFile> arquivos)
        {
            if (!arquivos.Any())
            {
                ViewData["Error"] = "Nenhum Arquivo foi selecionado";
                return View("Index");
            }

            var arquivoExtensao = arquivos.Any(a => !a.FileName.Contains(".ofx"));

            if (arquivoExtensao)
            {
                ViewData["Error"] = $"A Extensão do(s) arquivo é invalida, favor carregar somente arquivo do tipo ofx!";
                return View("Index");
            }

             var transacoes = ProcessamentoDoArquivo.LerArquivos(arquivos);

            var extratoBancario = ConverterTransacoesBancariaParaViewModel.Converter(transacoes);

            return View("CarregarTransacoesBancarias", extratoBancario);
        }
    }
}

src/ContabilizaJa.WebApp/Views/ExtratoBancario/Index.cshtml
@model IEnumerable<ContabilizaJa.Movimentacao.Application.ExtratoBancarioViewModels>

<h2>Extratos bancários</h2>

<form method="get" asp-action="Get">
    <table class="table">
        <thead>
            <tr>
                <th scope="col">Data do registro</th>
                <th scope="col">Periodo do extrato</th>
                <th scope="col">Ações</th>
            </tr>
        </thead>
        <tbody>
            @if (Model.Any())
                {
                    @foreach (var extrato in Model)
                    {
                        <tr>
                            <td>@extrato.DataRegistro</td>
                            <td>@extrato.Periodo</td>
                            <td>
                                <button type="submit" class="btn btn-primary" name="Id" asp-action="Get" asp-route-id="@extrato.Id">Ver Extrato</button>
                                <button type="submit" class="btn btn-primary" asp-action="Delete" asp-route-id="@extrato.Id">Remover Extrato</button>
                            </td>
                        </tr>
                    }
                }
                else
                {
                    <tr>
                        <td colspan="3">Nenhum registro foi encontrado.</td>
                    </tr>
                }
        </tbody>
    </table>
</form>

src/ContabilizaJa.WebApp/Views/ExtratoBancario/Transacoes/TransacoesBancarias.cshtml
@model ContabilizaJa.Movimentacao.Application.ExtratoBancarioViewModels;

<h5 style="margin: 40px 0">@Model.Periodo</h5>

<div class="container">
    <div class="row">
        <table class="table">
            <thead>
                <tr>
                    <th scope="col">Data</th>
                    <th scope="col">Tipo da Transação</th>
                    <th scope="col">Valor</th>
                    <th scope="col">Descrição</th>
                </tr>
            </thead>
            @if (Model.Transacoes.Count > 0)
            {
            <tbody>
                @foreach (var transacao in Model.Transacoes)
                {
                <tr>
                    <th scope="row">@transacao.Data</th>
                    <td>@transacao.Tipo</td>
                    <td>@transacao.Valor</td>
                    <td>@transacao.Descricao</td>
                </tr>
                }
            </tbody>
            }
            else
            {
            <tbody>
                <tr>
                    <td>Nenhum registro foi encontrado.</td>
                </tr>
            </tbody>
            }
        </table>
    </div>
</div>

src/ContabilizaJa.WebApp/Views/Home/Index.cshtml
@{
    ViewData["Title"] = "Home Page";
}

<div class="text-center">
    <h1 class="display-4">Welcome</h1>
    <p>Learn about <a href="https://docs.microsoft.com/aspnet/core">building Web apps with ASP.NET Core</a>.</p>
</div>

src/ContabilizaJa.WebApp/Views/ProcessarArquivo/CarregarTransacoesBancarias.cshtml
<div class="container">
    <h2>Resultado das transações</h2>

    <div class="message" style="display: none;">
        <div class="alert" role="alert"><span></span></div>
    </div>

    <partial name="~/Views/Shared/Partial/LoadValidationMessage.cshtml" />

    <div class="my-4">
        <button id="salvar" class="btn btn-success">Salvar Dados</button>
        <button class="btn btn-primary" asp-action="Index">Voltar</button>
    </div>

    @if (ViewData["Error"] == null)
    {
        <partial name="~/Views/ProcessarArquivo/Partial/Transacoes.cshtml" />
    }
</div>

<script src="~/js/extratoBancario.js" asp-append-version="true"></script>

src/ContabilizaJa.WebApp/Views/ProcessarArquivo/Index.cshtml
@{
    ViewData["Title"] = "BankLine";
}
<div class="container">

    <h2>Formulario para envio do arquivo</h2>

    <partial name="~/Views/Shared/Partial/LoadValidationMessage.cshtml" />

    <form class="my-4" asp-controller="ProcessarArquivo" asp-action="CarregarArquivo" enctype="multipart/form-data" method="post">
        <div class="mb-3">
            <label for="formFile" class="form-label">Selecionar Arquivo OFX</label>
            <input class="form-control" type="file" name="arquivos" id="formFile" multiple>
        </div>
        <input type="submit" class="btn btn-primary" value="Processar extrato">
    </form>
</div>

src/ContabilizaJa.WebApp/Views/ProcessarArquivo/Partial/Transacoes.cshtml
@model ContabilizaJa.Movimentacao.Application.ExtratoBancarioViewModels;

<table class="table">
    <thead>
        <tr>
            <th scope="col">Data</th>
            <th scope="col">Tipo da Transação</th>
            <th scope="col">Valor</th>
            <th scope="col">Descrição</th>
        </tr>
    </thead>
    @if (Model.Transacoes.Count > 0)
    {
        <tbody>
            @foreach (var transaction in Model.Transacoes)
            {
                <tr>
                    <th scope="row">@transaction.Data</th>
                        <td>@transaction.Tipo</td>
                        <td>@transaction.Valor</td>
                        <td>@transaction.Descricao</td>
                </tr>
            }
        </tbody>
    }
    else
    {
        <tbody>
            <tr>
                <td>Nenhum registro foi encontrado.</td>
            </tr>
        </tbody>
    }
</table>

src/ContabilizaJa.WebApp/Views/Shared/Partial/LoadValidationMessage.cshtml
@if (ViewData["Error"] != null)
{
    <div class="alert alert-danger" role="alert">
        @ViewData["Error"]
    </div>
}
@if (ViewData["Success"] != null)
{
    <div class="alert alert-success" role="alert">
        @ViewData["Success"]
    </div>
}

src/ContabilizaJa.WebApp/Views/Shared/_Layout.cshtml
<!DOCTYPE html>
<html>
<head>
    <meta charset="utf-8" />
    <meta name="viewport" content="width=device-width, initial-scale=1.0" />
    <title>@ViewData["Title"] - ContabilizaJa.WebApp</title>

    <environment include="Development">
        <link rel="stylesheet" href="~/lib/bootstrap/dist/css/bootstrap.css" />
    </environment>
    <environment exclude="Development">
        <link rel="stylesheet" href="https://stackpath.bootstrapcdn.com/bootstrap/4.3.1/css/bootstrap.min.css"
              asp-fallback-href="~/lib/bootstrap/dist/css/bootstrap.min.css"
              asp-fallback-test-class="sr-only" asp-fallback-test-property="position" asp-fallback-test-value="absolute"
              crossorigin="anonymous"
              integrity="sha384-ggOyR0iXCbMQv3Xipma34MD+dH/1fQ784/j6cY/iJTQUOhcWr7x9JvoRxT2MZw1T" />
    </environment>
    <link rel="stylesheet" href="~/css/site.css" />
</head>
<body>
    <header>
        <nav class="navbar navbar-expand-sm navbar-toggleable-sm navbar-light bg-white border-bottom box-shadow mb-3">
            <div class="container">
                <a class="navbar-brand" asp-area="" asp-controller="Home" asp-action="Index">ContabilizaJa</a>
                <button class="navbar-toggler" type="button" data-toggle="collapse" data-target=".navbar-collapse" aria-controls="navbarSupportedContent"
                        aria-expanded="false" aria-label="Toggle navigation">
                    <span class="navbar-toggler-icon"></span>
                </button>
                <div class="navbar-collapse collapse d-sm-inline-flex flex-sm-row-reverse">
                    <ul class="navbar-nav flex-grow-1">
                        <li class="nav-item">
                            <a class="nav-link text-dark" asp-area="" asp-controller="ProcessarArquivo" asp-action="Index">Início</a>
                        </li>
                        <li class="nav-item">
                            <a class="nav-link text-dark" asp-area="" asp-controller="ExtratoBancario" asp-action="Index">Extratos Bancários</a>
                        </li>
                    </ul>
                </div>
            </div>
        </nav>
    </header>
    <div class="container">
        <partial name="_CookieConsentPartial" />
        <main role="main" class="pb-3">
            @RenderBody()
        </main>
    </div>

    <footer class="border-top footer text-muted">
        <div class="container">
            &copy; 2022 - ContabilizaJa.WebApp - <a asp-area="" asp-controller="Home" asp-action="Privacy">Privacy</a>
        </div>
    </footer>

    <environment include="Development">
        <script src="~/lib/jquery/dist/jquery.js"></script>
        <script src="~/lib/bootstrap/dist/js/bootstrap.bundle.js"></script>
    </environment>
    <environment exclude="Development">
        <script src="https://cdnjs.cloudflare.com/ajax/libs/jquery/3.3.1/jquery.min.js"
                asp-fallback-src="~/lib/jquery/dist/jquery.min.js"
                asp-fallback-test="window.jQuery"
                crossorigin="anonymous"
                integrity="sha256-FgpCb/KJQlLNfOu91ta32o/NMZxltwRo8QtmkMRdAu8=">
        </script>
        <script src="https://stackpath.bootstrapcdn.com/bootstrap/4.3.1/js/bootstrap.bundle.min.js"
                asp-fallback-src="~/lib/bootstrap/dist/js/bootstrap.bundle.min.js"
                asp-fallback-test="window.jQuery && window.jQuery.fn && window.jQuery.fn.modal"
                crossorigin="anonymous"
                integrity="sha384-xrRywqdh3PHs8keKZN+8zzc5TX0GRTLCcmivcbNJWm2rs5C8PRhcEn3czEjhAO9o">
        </script>
    </environment>
    <script src="~/js/site.js" asp-append-version="true"></script>

    @RenderSection("Scripts", required: false)
</body>
</html>